In [1]:
! pip install pandas scikit-learn
! pip install matplotlib seaborn
! pip install numpy

! pip install transformers dataset 
! pip install torch
! pip install tf-keras
! pip install pandas 
! pip install ffmpeg-python

Logistic Regression CLassification

In [23]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import time
import joblib

data = pd.read_csv(r"C:\Users\Anjali\Downloads\datasets_female.csv", delimiter='\t')
data.columns = data.columns.str.strip()


X = data[['Positive', 'Neutral', 'Negative', 'Pitch', 'Pitch Variance', 'Amplitude']] 
y = data['Emotion'] 


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000, C=100, class_weight='balanced')


start_time = time.time()
model.fit(X_scaled, y)
end_time = time.time()
training_time = end_time - start_time   

y_pred = model.predict(X_scaled)


accuracy = accuracy_score(y, y_pred)


print(f"Training Time: {training_time:.2f} seconds")
print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred))
print("\nClassification Report:")
print(classification_report(y, y_pred))
print(f"Overall Accuracy: {accuracy:.4f}")

joblib.dump(model, 'EmotionAIModel.joblib')
joblib.dump(scaler, 'scaler.joblib')

print("\nModel and scaler saved successfully!")


Training Time: 0.02 seconds

Confusion Matrix:
[[6 1 0 1 2]
 [1 7 0 2 0]
 [0 1 9 1 1]
 [0 0 1 6 1]
 [2 1 1 2 2]]

Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.60      0.63        10
           1       0.70      0.70      0.70        10
           2       0.82      0.75      0.78        12
           3       0.50      0.75      0.60         8
           4       0.33      0.25      0.29         8

    accuracy                           0.62        48
   macro avg       0.60      0.61      0.60        48
weighted avg       0.63      0.62      0.62        48

Overall Accuracy: 0.6250

Model and scaler saved successfully!


In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
import time
import joblib

data = pd.read_csv(r"C:\Users\Anjali\Downloads\datasets_female.csv", delimiter='\t')
data.columns = data.columns.str.strip()


X = data[['Positive', 'Neutral', 'Negative', 'Pitch', 'Pitch Variance', 'Amplitude']] 
y = data['Emotion']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


start_time = time.time()

rf_model = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
rf_model.fit(X_scaled, y)

end_time = time.time()
training_time = end_time - start_time

y_pred = rf_model.predict(X_scaled)


accuracy = accuracy_score(y, y_pred)

print(f"Training Time: {training_time:.2f} seconds")
print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred))
print("\nClassification Report:")
print(classification_report(y, y_pred))
print(f"Overall Accuracy: {accuracy:.4f}")


joblib.dump(rf_model, 'RandomForestEmotionModel.joblib')
joblib.dump(scaler, 'scaler.joblib')

print("\nModel and scaler saved successfully!")


Training Time: 0.11 seconds

Confusion Matrix:
[[10  0  0  0  0]
 [ 0  9  1  0  0]
 [ 0  1 11  0  0]
 [ 0  0  1  7  0]
 [ 2  0  2  1  3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       0.90      0.90      0.90        10
           2       0.73      0.92      0.81        12
           3       0.88      0.88      0.88         8
           4       1.00      0.38      0.55         8

    accuracy                           0.83        48
   macro avg       0.87      0.81      0.81        48
weighted avg       0.86      0.83      0.82        48

Overall Accuracy: 0.8333

Model and scaler saved successfully!


In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
import time
import joblib

data = pd.read_csv(r"C:\Users\Anjali\Downloads\datasets_female.csv", delimiter='\t')
data.columns = data.columns.str.strip()


X = data[['Positive', 'Neutral', 'Negative', 'Pitch', 'Pitch Variance', 'Amplitude']] 
y = data['Emotion']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


start_time = time.time()

rf_model = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
rf_model.fit(X_scaled, y)

end_time = time.time()
training_time = end_time - start_time

y_pred = rf_model.predict(X_scaled)


accuracy = accuracy_score(y, y_pred)

print(f"Training Time: {training_time:.2f} seconds")
print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred))
print("\nClassification Report:")
print(classification_report(y, y_pred))
print(f"Overall Accuracy: {accuracy:.4f}")


joblib.dump(rf_model, 'F_RandomForestEmotionModel.joblib')
joblib.dump(scaler, 'scaler.joblib')

print("\nModel and scaler saved successfully!")


Training Time: 0.15 seconds

Confusion Matrix:
[[10  0  0  0  0]
 [ 0  9  1  0  0]
 [ 0  1 11  0  0]
 [ 0  0  1  7  0]
 [ 2  0  2  1  3]]

Classification Report:
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        10
           1       0.90      0.90      0.90        10
           2       0.73      0.92      0.81        12
           3       0.88      0.88      0.88         8
           4       1.00      0.38      0.55         8

    accuracy                           0.83        48
   macro avg       0.87      0.81      0.81        48
weighted avg       0.86      0.83      0.82        48

Overall Accuracy: 0.8333

Model and scaler saved successfully!


In [3]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
import time
import joblib

data = pd.read_csv(r"C:\Users\Anjali\Downloads\datasets_male.csv", delimiter='\t')
data.columns = data.columns.str.strip()


X = data[['Positive', 'Neutral', 'Negative', 'Pitch', 'Pitch Variance', 'Amplitude']] 
y = data['Emotion']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


start_time = time.time()

rf_model = RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42)
rf_model.fit(X_scaled, y)

end_time = time.time()
training_time = end_time - start_time


y_pred = rf_model.predict(X_scaled)

accuracy = accuracy_score(y, y_pred)


print(f"Training Time: {training_time:.2f} seconds")
print("\nConfusion Matrix:")
print(confusion_matrix(y, y_pred))
print("\nClassification Report:")
print(classification_report(y, y_pred))
print(f"Overall Accuracy: {accuracy:.4f}")


joblib.dump(rf_model, 'M_RandomForestEmotionModel.joblib')
joblib.dump(scaler, 'scaler.joblib')

print("\nModel and scaler saved successfully!")


Training Time: 0.12 seconds

Confusion Matrix:
[[9 0 0 0 1]
 [0 9 0 0 1]
 [0 1 9 1 1]
 [0 0 0 8 0]
 [1 0 1 1 5]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        10
           1       0.90      0.90      0.90        10
           2       0.90      0.75      0.82        12
           3       0.80      1.00      0.89         8
           4       0.62      0.62      0.62         8

    accuracy                           0.83        48
   macro avg       0.82      0.83      0.83        48
weighted avg       0.84      0.83      0.83        48

Overall Accuracy: 0.8333

Model and scaler saved successfully!
